// Device "touched" flags — exact port of device.h / device.c

#[derive(Clone, Debug, Default)]
pub struct DeviceFlags {
    pub display_touched: i32,
    pub contrast_touched: bool,
    pub disp_test_touched: bool,
    pub crc_touched: bool,
    pub power_status_touched: bool,
    pub power_ctrl_touched: bool,
    pub mode_touched: bool,
    pub ann_touched: bool,
    pub baud_touched: bool,
    pub card_ctrl_touched: bool,
    pub card_status_touched: bool,
    pub ioc_touched: bool,
    pub tcs_touched: bool,
    pub rcs_touched: bool,
    pub rbr_touched: bool,
    pub tbr_touched: bool,
    pub sreq_touched: bool,
    pub ir_ctrl_touched: bool,
    pub base_off_touched: bool,
    pub lcr_touched: bool,
    pub lbr_touched: bool,
    pub scratch_touched: bool,
    pub base_nibble_touched: bool,
    pub unknown_touched: bool,
    pub t1_ctrl_touched: bool,
    pub t2_ctrl_touched: bool,
    pub unknown2_touched: bool,
    pub t1_touched: bool,
    pub t2_touched: bool,
    pub speaker_counter: i32,
}
